#include "bsp_ewm201.h"
#include "sys_task.h"

#if ENABLE_BSP_EWM201

#include "usart.h" // Ensure this is generated by CubeMX
#include <stdio.h>
#include <string.h>

static void EWM201_int(void);

void EWM201_Init(void)
{
    EWM201_int();
}

static void EWM201_int(void)
{
    GPIO_InitTypeDef gpio_init_struct;
    __HAL_RCC_GPIOC_CLK_ENABLE();

    gpio_init_struct.Pin = GPIO_PIN_0;
    gpio_init_struct.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_struct.Pull = GPIO_PULLUP;
    gpio_init_struct.Speed = GPIO_SPEED_FREQ_MEDIUM;
    HAL_GPIO_Init(GPIOC, &gpio_init_struct);

    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_0, GPIO_PIN_SET);
}

void EWM201_PowerDown(uint8_t power_down)
{
    if (power_down)
    {
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_0, GPIO_PIN_SET);
    }
    else
    {
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_0, GPIO_PIN_RESET);
    }
}

#endif // ENABLE_BSP_EWM201
